test-python2:
	python ./test_nwb.py

test-python3:
	python3 ./test_nwb.py

test-python2-silent:
	@echo "piping output to 'output.txt'"
	@python ./test_nwb.py > ./output.txt

test-python3-silent:
	@echo "piping output to 'output.txt'"
	@python3 ./test_nwb.py > ./output.txt
